import 'package:yaml/yaml.dart';
import 'dart:io';

String scriptify(String content, String dir){
  Map opt = loadYaml(content);
  String script = '//generated by extendo \n';
  
  opt['style']!=null?opt['style'].forEach((key, value){ 
    opt['style'][key]!=null?script+='document.body.style.'+key+'="'+value+'";\n':0;
  }):0;

  opt['scripts']!=null?opt['scripts'].forEach((e){ 
    script += File(dir+'/'+e).readAsStringSync() + '\n';
  }):0;
  return script;
}